### PR TITLE
Improve portability tweaks

### PR DESCRIPTION
**Pull request by lostthetrail**
1. Changed async.forEach to async.each as it is deprecated and will eventually be an upgrade issue.
2. Remove unnecessary iteration which produced 'partialundefined' as a final check, rather than empty.
3. Used path to join file structure for debugging messages.
4. Remove redundant code and reuse.

### CODE REVIEW

**Comment by pcardune** [comment]
Looks good, but can you switch to tabs instead of spaces? I personally prefer spaces, but I'd rather do the conversion to spaces for the entire codebase in a single commit.

**Comment by lostthetrail** [comment]
Back to you @pcardune.

**Comment by lostthetrail** [comment]
Feel free to just close this PR and merge #91. It includes all these commits, I just wanted to make sure you had the code separated for readability.

**Comment by pcardune** [comment]
Thanks, will merge #91

**Pull request closed without merging**
